"""Rename arduino_components again

Revision ID: 64db5bcd7a97
Revises: c1cd7def0893
Create Date: 2025-05-13 01:35:44.328657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64db5bcd7a97'
down_revision = 'c1cd7def0893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arduino_components',
    sa.Column('arduino_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arduino_id'], ['arduino.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('arduino_id', 'component_id')
    )
    op.drop_table('arduino__components')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arduino__components',
    sa.Column('arduino_id', sa.INTEGER(), nullable=False),
    sa.Column('component_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['arduino_id'], ['arduino.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('arduino_id', 'component_id')
    )
    op.drop_table('arduino_components')
    # ### end Alembic commands ###
