"""Added quantity of components

Revision ID: c1cd7def0893
Revises: c21644a66941
Create Date: 2025-05-13 01:33:36.866292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1cd7def0893'
down_revision = 'c21644a66941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arduino__components',
    sa.Column('arduino_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arduino_id'], ['arduino.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('arduino_id', 'component_id')
    )
    op.drop_table('arduino_components')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arduino_components',
    sa.Column('arduino_id', sa.INTEGER(), nullable=False),
    sa.Column('component_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['arduino_id'], ['arduino.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('arduino_id')
    )
    op.drop_table('arduino__components')
    # ### end Alembic commands ###
