"""rename arduino_components

Revision ID: c21644a66941
Revises: 7143fa621e9b
Create Date: 2025-05-13 01:30:10.055137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21644a66941'
down_revision = '7143fa621e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arduino_components',
    sa.Column('arduino_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arduino_id'], ['arduino.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('arduino_id')
    )
    op.drop_table('arduino__components')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arduino__components',
    sa.Column('arduino_id', sa.INTEGER(), nullable=False),
    sa.Column('component_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['arduino_id'], ['arduino.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('arduino_id')
    )
    op.drop_table('arduino_components')
    # ### end Alembic commands ###
